#! /bin/sh

sxhkd &

# autostart
# redshift -g 0.9 -m randr -t 4500:3000 &
killall picom 2>/dev/null; picom -b &
killall dunst 2>/dev/null; dunst &

## desktop/laptop
## change the display type when necessary
~/.config/polybar/launch_polybar DP main-bar
~/.config/polybar/launch_polybar HDMI sec-bar
## virtualbox
~/.config/polybar/launch_polybar Virtual vb-bar

n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 10 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))`
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

bspc config border_width         2
bspc config top_padding          -2
bspc config window_gap           3
bspc config split_ratio          0.52
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#ffc300"
bspc config presel_feedback_color	"#5e81ac"

# Dropdown term with Alacritty
bspc rule -a Alacritty:ddterm state=floating sticky=on center=on rectangle=720x294+0+0
# Floating term
bspc rule -a Alacritty:floatterm state=floating sticky=on center=on rectangle=360x220+0+0
bspc rule -a Alacritty:vifm state=floating center=on rectangle=720x588+0+0
# Joplin
bspc rule -a Joplin desktop='9'
bspc rule -a Alacritty:joplin desktop='9'
# Zathura
bspc rule -a Zathura state=tiled
# Slack
bspc rule -a Slack state=floating center=on rectangle=1800x1000+0+0

bspc rule -a Emacs state=tiled
