#! /bin/sh

sxhkd &

# autostart
redshift -g 0.9 -m randr -t 4500:3000 &
killall picom 2>dev/null; picom -b &
killall dunst 2>/dev/null; dunst &
# change vb-bar for non virtualbox
killall polybar 2>/dev/null; polybar vb-bar &

bspc monitor Virtual-1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#93ae7c"
bspc config presel_feedback_color	"#5e81ac"

# Dropdown term with Alacritty
bspc rule -a Alacritty:ddterm state=floating sticky=on center=on rectangle=720x294+0+0
# Floating term
bspc rule -a Alacritty:floatterm state=floating sticky=on center=on rectangle=360x220+0+0
bspc rule -a Alacritty:vifm state=floating center=on rectangle=720x588+0+0
# Joplin
bspc rule -a Joplin desktop='0'
bspc rule -a Alacritty:joplin desktop='0'
# Zathura
bspc rule -a Zathura state=tiled
