#!/usr/bin/env sh
# Give a battery name (e.g. BAT0) as an argument.

BAT="${BLOCK_INSTANCE:-BAT0}" 
capacity=$(cat /sys/class/power_supply/"$BAT"/capacity) || exit
status=$(cat /sys/class/power_supply/"$BAT"/status)

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "$status"
esac

if [ "$capacity" -le 25 ]; then
	color="#ff0000"
else
    color="#999999"
fi

[ "$status" = "Charging" ] && color="#ebdbb2"

printf "<span color='%s'>%s %s</span>\n" "$color" "" $capacity"%"
